# Generated by Django 3.2.8 on 2021-10-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211013_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Cart'),
        ),
    ]
