# Generated by Django 3.2.9 on 2021-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20211025_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
