# Generated by Django 3.2.9 on 2021-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_userprofile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default='', max_length=10, verbose_name='Phone Number'),
        ),
    ]
