# Generated by Django 3.2.8 on 2021-10-13 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Product Name')),
                ('excerpt', models.TextField(default='', max_length=500, verbose_name='Short Description')),
                ('description', models.TextField(default='', max_length=5000, verbose_name='Long Description')),
                ('price', models.IntegerField(verbose_name='Price (in Rupees)')),
                ('discount', models.IntegerField(blank=True, verbose_name='Discount (in percent)')),
                ('stocks', models.IntegerField(blank=True, verbose_name='Stocks Left')),
                ('features', models.JSONField(blank=True, verbose_name='Product Features')),
                ('video', models.FileField(blank=True, null=True, upload_to='product_videos/{id}/', validators=[shop.validators.validate_video_size, shop.validators.validate_video_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date & Time updated')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Product Added by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Sub Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500, verbose_name='Product Review')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Review Date & Time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Related Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=800, upload_to='product_images/False/', verbose_name='Product Image', width_field=800)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Related Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='Product Sub-Category'),
        ),
    ]
