# Generated by Django 3.2.8 on 2021-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='stars',
            field=models.IntegerField(null=True, verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, null=True, verbose_name='Product Features'),
        ),
    ]
