# Generated by Django 3.2.8 on 2021-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211016_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/<built-in function id>/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/<built-in function id>/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/<built-in function id>/', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/<built-in function id>/', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/<built-in function id>/', verbose_name='Image 6'),
        ),
    ]
