# Generated by Django 3.2.8 on 2021-10-16 08:30

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211016_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='replacement',
            field=models.CharField(default='No', max_length=20, verbose_name='Replacement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/<built-in function id>/', validators=[shop.validators.validate_video_size, shop.validators.validate_video_extension]),
        ),
    ]
