# Generated by Django 3.2.9 on 2021-11-11 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_alter_product_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='stars',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Stars'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='[]', max_length=10000, null=True, verbose_name='Items')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='', max_length=500, null=True, verbose_name='Full Address')),
                ('city', models.CharField(default='', max_length=500, null=True, verbose_name='City')),
                ('state', models.CharField(default='', max_length=500, null=True, verbose_name='State')),
                ('zip_code', models.PositiveIntegerField(verbose_name='Zip Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User')),
            ],
        ),
    ]
