# Generated by Django 3.2.9 on 2021-11-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211111_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
