# Generated by Django 3.2.9 on 2021-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211111_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date & Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='razp_amount',
            field=models.PositiveIntegerField(null=True, verbose_name='RazorPay Amount (in Rs.)'),
        ),
        migrations.AddField(
            model_name='order',
            name='razp_order_id',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='RazorPay Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='razp_payment_id',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='RazorPay Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='razp_signature',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='RazorPay Signature'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending'), ('refund', 'Refund')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
